export const PROVINCES = [
  'Eastern Cape',
  'Free State',
  'Gauteng',
  'KwaZulu-Natal',
  'Limpopo',
  'Mpumalanga',
  'North West',
  'Northern Cape',
  'Western Cape',
];

export const PHASES = [
  'Foundation Phase (Gr R-3)',
  'Intermediate Phase (Gr 4-6)',
  'Senior Phase (Gr 7-9)',
  'FET Phase (Gr 10-12)',
  'LSEN / Special Needs',
];

export const SUBJECTS = [
  'Afrikaans',
  'Agricultural Sciences',
  'Accounting',
  'Business Studies',
  'Computer Applications Technology',
  'Consumer Studies',
  'Design',
  'Dramatic Arts',
  'Economics',
  'Engineering Graphics & Design',
  'English',
  'Geography',
  'History',
  'Hospitality Studies',
  'Information Technology',
  'IsiNdebele',
  'IsiXhosa',
  'IsiZulu',
  'Life Orientation',
  'Life Sciences',
  'Mathematics',
  'Mathematical Literacy',
  'Music',
  'Natural Sciences',
  'Physical Sciences',
  'Religion Studies',
  'SePedi',
  'SeSotho',
  'SetSwana',
  'SiSwati',
  'Social Sciences',
  'Technology',
  'Tourism',
  'Tshivenda',
  'Visual Arts',
  'Xitsonga',
];

export const SA_ID_TYPES = ['SA ID', 'Passport', 'Asylum Seeker Permit'];
