// src/lib/generateDocxBlob.ts
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Footer } from 'docx';

interface CVData {
  personal: { full_name?: string; email?: string; phone?: string; address?: string; bio?: string };
  education: { institution: string; qualification: string; year: string }[];
  experience: { school: string; role: string; from: string; to: string; description: string }[];
  skills: { subjects?: string[]; soft_skills?: string[]; languages?: string[] };
  references?: { name: string; title: string; organisation: string; phone: string; email: string; relationship: string }[];
  template: string;
}

function bulletPoints(lines: string[]): Paragraph[] {
  return lines.map(line => new Paragraph({
    bullet: { level: 0 },
    children: [new TextRun(line.trim())],
  }));
}

export async function generateDocxBlob(data: CVData, user?: { id: string; email: string }): Promise<Blob> {
  const { personal, education, experience, skills, references } = data;

  const children: any[] = [];

  // Name
  children.push(new Paragraph({
    text: personal.full_name || 'Your Name',
    heading: HeadingLevel.TITLE,
    alignment: AlignmentType.CENTER,
    spacing: { after: 120 },
  }));

  // Contact line
  const contactParts = [personal.email, personal.phone, personal.address].filter(Boolean);
  if (contactParts.length) {
    children.push(new Paragraph({
      children: contactParts.map((part, idx) => new TextRun((idx > 0 ? ' | ' : '') + part)),
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
    }));
  }

  // Bio
  if (personal.bio) {
    children.push(new Paragraph({ text: 'Professional Summary', heading: HeadingLevel.HEADING_2, spacing: { before: 160, after: 80 } }));
    children.push(new Paragraph(personal.bio));
  }

  // Experience
  const validExp = experience.filter(e => e.school);
  if (validExp.length) {
    children.push(new Paragraph({ text: 'Teaching Experience', heading: HeadingLevel.HEADING_2, spacing: { before: 160, after: 80 } }));
    for (const exp of validExp) {
      children.push(new Paragraph({ text: exp.role, bold: true, spacing: { after: 0 } }));
      children.push(new Paragraph(`${exp.school} · ${exp.from || ''} – ${exp.to || ''}`));
      const descLines = exp.description.split('\n').filter(l => l.trim());
      if (descLines.length) children.push(...bulletPoints(descLines));
      children.push(new Paragraph({ text: '' }));
    }
  }

  // Education
  const validEdu = education.filter(e => e.institution);
  if (validEdu.length) {
    children.push(new Paragraph({ text: 'Education', heading: HeadingLevel.HEADING_2, spacing: { before: 160, after: 80 } }));
    for (const edu of validEdu) {
      children.push(new Paragraph({ text: edu.qualification, bold: true, spacing: { after: 0 } }));
      children.push(new Paragraph(`${edu.institution} · ${edu.year}`));
    }
  }

  // Skills
  const skillsChildren: any[] = [];
  if (skills.subjects?.length) {
    skillsChildren.push(new Paragraph({ text: 'Subjects', bold: true, spacing: { after: 40 } }));
    skillsChildren.push(...bulletPoints(skills.subjects));
  }
  if (skills.soft_skills?.length) {
    skillsChildren.push(new Paragraph({ text: 'Professional Skills', bold: true, spacing: { before: 80, after: 40 } }));
    skillsChildren.push(...bulletPoints(skills.soft_skills));
  }
  if (skills.languages?.length) {
    skillsChildren.push(new Paragraph({ text: 'Languages', bold: true, spacing: { before: 80, after: 40 } }));
    skillsChildren.push(...bulletPoints(skills.languages));
  }
  if (skillsChildren.length) {
    children.push(new Paragraph({ text: 'Skills', heading: HeadingLevel.HEADING_2, spacing: { before: 160, after: 80 } }));
    children.push(...skillsChildren);
  }

  // References (new page)
  const validRefs = (references || []).filter(r => r.name);
  if (validRefs.length) {
    children.push(new Paragraph({ pageBreakBefore: true, text: '' }));
    children.push(new Paragraph({ text: 'References', heading: HeadingLevel.HEADING_2, spacing: { before: 0, after: 80 } }));
    for (const ref of validRefs) {
      children.push(new Paragraph({ text: ref.name, bold: true, spacing: { after: 0 } }));
      children.push(new Paragraph([ref.title, ref.organisation].filter(Boolean).join(' · ')));
      children.push(new Paragraph(`Phone: ${ref.phone} · Email: ${ref.email}`));
      if (ref.relationship) children.push(new Paragraph(ref.relationship));
      children.push(new Paragraph({ text: '' }));
    }
  }

  // Footer – abuse prevention
  const footer = new Footer({
    children: [
      new Paragraph({
        children: [
          new TextRun({
            text: `Generated by Crosssa – www.crosssa.co.za${user ? ` (User: ${user.email})` : ''}`,
            size: 18,
            color: '999999',
          }),
        ],
        alignment: AlignmentType.CENTER,
      }),
    ],
  });

  const doc = new Document({
    styles: { default: { document: { run: { font: "Calibri", size: 24 } } } },
    sections: [{
      properties: {
        page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } },
      },
      children,
      footers: { default: footer },
    }],
    customProperties: user ? [
      { name: 'GeneratedBy', value: user.id },
      { name: 'GeneratedAt', value: new Date().toISOString() },
    ] : [],
  });

  return await Packer.toBlob(doc);
}