import { GraduationCap, MapPin, BookOpen, Star, Phone, Mail } from 'lucide-react';

interface Props {
  educator: any;
  watermark?: boolean;
}

export default function CVPreview({ educator, watermark = false }: Props) {
  return (
    <div className="bg-white relative font-[sans-serif] p-8 min-h-[297mm]" style={{ fontFamily: 'Georgia, serif' }}>
      {watermark && (
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none opacity-10 z-10" style={{ transform: 'rotate(-30deg)' }}>
          <p className="text-6xl font-black text-primary tracking-widest">EduCross</p>
        </div>
      )}

      <div className="flex items-start gap-4 mb-6 pb-6 border-b-2 border-primary">
        <div className="flex-1">
          <h1 className="text-3xl font-bold text-foreground mb-1">{educator.full_name || 'Your Name'}</h1>
          <p className="text-lg text-primary font-medium">{educator.phase || 'Educator'}</p>
          <div className="flex flex-wrap items-center gap-3 mt-2 text-sm text-muted-foreground">
            {educator.current_province && (
              <span className="flex items-center gap-1"><MapPin className="w-3.5 h-3.5" />{educator.current_province}</span>
            )}
            {educator.current_school && (
              <span className="flex items-center gap-1">· {educator.current_school}</span>
            )}
          </div>
        </div>
        <div className="w-20 h-20 rounded-full bg-primary/10 flex items-center justify-center shrink-0 overflow-hidden border-2 border-primary/20">
          {educator.avatar_url
            ? <img src={educator.avatar_url} alt={educator.full_name} className="w-full h-full object-cover" />
            : <GraduationCap className="w-10 h-10 text-primary" />
          }
        </div>
      </div>

      {educator.bio && (
        <section className="mb-5">
          <h2 className="text-sm font-bold uppercase tracking-widest text-primary mb-2">Professional Summary</h2>
          <p className="text-sm text-foreground leading-relaxed">{educator.bio}</p>
        </section>
      )}

      {educator.subjects?.length > 0 && (
        <section className="mb-5">
          <h2 className="text-sm font-bold uppercase tracking-widest text-primary mb-2 flex items-center gap-2">
            <BookOpen className="w-3.5 h-3.5" />Subjects
          </h2>
          <div className="flex flex-wrap gap-2">
            {educator.subjects.map((s: string) => (
              <span key={s} className="px-3 py-1 bg-primary/10 text-primary text-xs rounded-full font-medium border border-primary/20">{s}</span>
            ))}
          </div>
        </section>
      )}

      <div className="grid grid-cols-2 gap-5">
        <section>
          <h2 className="text-sm font-bold uppercase tracking-widest text-primary mb-3">Experience</h2>
          <div className="space-y-2">
            {educator.years_experience && (
              <div className="flex items-center gap-2">
                <Star className="w-3.5 h-3.5 text-muted-foreground" />
                <p className="text-sm text-foreground">{educator.years_experience} years teaching</p>
              </div>
            )}
            {educator.current_school && (
              <div>
                <p className="text-sm font-medium text-foreground">{educator.current_school}</p>
                <p className="text-xs text-muted-foreground">{educator.town && `${educator.town}, `}{educator.current_province}</p>
              </div>
            )}
          </div>
        </section>

        <section>
          <h2 className="text-sm font-bold uppercase tracking-widest text-primary mb-3">Location</h2>
          <div className="space-y-1">
            <p className="text-sm text-foreground">Current: <span className="font-medium">{educator.current_province || '—'}</span></p>
            {educator.preferred_provinces?.length > 0 && (
              <div>
                <p className="text-sm text-muted-foreground">Open to:</p>
                <p className="text-sm font-medium text-foreground">{educator.preferred_provinces.join(', ')}</p>
              </div>
            )}
          </div>
        </section>
      </div>

      <div className="mt-8 pt-5 border-t border-border">
        <p className="text-[10px] text-muted-foreground text-center">Generated by EduCross — South Africa's Teacher Transfer Platform</p>
      </div>
    </div>
  );
}
